'use client';
import {ReactNode} from 'react';
import Link from 'next/link';
import {Heart,Star,ArrowUpRight,Grid2X2,Video,Users,GraduationCap,PartyPopper,Music,Camera,Store,CircleDot,Laptop,Car,MapPin} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Checkbox} from '@/components/ui/checkbox';
import {categories,Space,money,hour,instantInfo} from './data';
import {useApp} from './context';
const icons=[Grid2X2,Video,Users,GraduationCap,PartyPopper,Music,Camera,Store,CircleDot,Laptop,Car];
export function Logo(){return <Link className="brand" href="/"><span className="brand-mark"><img src="/logo.jpeg" alt=""/></span>WELAA<span className="brand-dot">.</span></Link>}
export function Choice({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={typeof o==='string'?o:o.value} value={typeof o==='string'?o:o.value}>{typeof o==='string'?o:o.label}</SelectItem>)}</SelectContent></Select>}
export function Check({checked,onChange,children}:{checked:boolean;onChange:(v:boolean)=>void;children:ReactNode}){return <label className="check-row"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{children}</span></label>}
export function Categories({value,onChange}:{value:string;onChange:(c:string)=>void}){return <div className="categories" id="categories">{categories.map((c,i)=>{const Icon=icons[i];return <button key={c} onClick={()=>onChange(c)} className={'category '+(c===value?'active':'')}><Icon/><span>{c}</span></button>})}</div>}
export function SpaceCard({s,instant=false}:{s:Space;instant?:boolean}){const {data,favorite}=useApp(),info=instant?instantInfo(s,data):null;return <article className="space-card"><div className="card-photo"><Link href={'/spaces/'+s.id}><img src={s.image} alt={s.name} loading="lazy"/></Link>{info&&<span className="available"><i/> ว่างถึง {hour(info.end)}</span>}<button aria-label={(data.favorites.includes(s.id)?'เลิกบันทึก ':'บันทึก ')+s.name} aria-pressed={data.favorites.includes(s.id)} className={'favorite '+(data.favorites.includes(s.id)?'saved':'')} onClick={()=>favorite(s.id)}><Heart size={18} fill={data.favorites.includes(s.id)?'currentColor':'none'}/></button></div><Link href={'/spaces/'+s.id}><div className="card-title"><h3>{s.name}</h3><span>{s.rating>0?<><Star size={12}/>{s.rating.toFixed(2)}</>:'ใหม่'}</span></div><p className="location">{s.area} · {s.city}</p><div className="card-bottom"><span><b>฿{money(info?.price??s.price)}</b> / ชั่วโมง</span><small>{s.activities[0]}</small></div></Link></article>}
export function SectionHead({title,sub,eyebrow,href,live=false}:{title:string;sub?:string;eyebrow?:string;href?:string;live?:boolean}){return <div className="section-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}{live&&<i className="live-dot"/>}</h2>{sub&&<p>{sub}</p>}</div>{href&&<Link href={href}>ดูทั้งหมด <ArrowUpRight size={17}/></Link>}</div>}
export function Empty({title,sub,children}:{title:string;sub?:string;children?:ReactNode}){return <div className="empty"><MapPin size={32}/><h3>{title}</h3>{sub&&<p>{sub}</p>}{children}</div>}
