'use client';
import {useEffect,useState,useCallback} from 'react';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {Plus,Search,Compass,CalendarDays,UserRound} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Toaster,toast} from 'sonner';
import {AppContext} from './context';
import {spaces,initial,AppData,slotStatus,slotPrice} from './data';
import {Logo} from './ui';
import {Home,SearchPage,HowItWorks} from './views';
import {Detail} from './detail';
import {Wizard} from './wizard';
import {Account,HostCalendar} from './account';
import {supabase} from '@/lib/supabase';
function GoogleMark(){return <svg aria-hidden="true" viewBox="0 0 48 48" width="21" height="21"><path fill="#4285F4" d="M43.6 24.5c0-1.4-.1-2.8-.4-4.1H24v7.8h11a9.4 9.4 0 0 1-4.1 6.2v5.1h6.7c3.9-3.6 6-8.8 6-15Z"/><path fill="#34A853" d="M24 44c5.5 0 10.1-1.8 13.5-4.9l-6.7-5.1c-1.8 1.2-4.1 2-6.8 2-5.2 0-9.7-3.5-11.3-8.2H5.8v5.2A20 20 0 0 0 24 44Z"/><path fill="#FBBC05" d="M12.7 27.8a12 12 0 0 1 0-7.6V15H5.8a20 20 0 0 0 0 18Z"/><path fill="#EA4335" d="M24 12.1c3 0 5.7 1 7.8 3.1l5.8-5.8C34.1 6.1 29.5 4 24 4A20 20 0 0 0 5.8 15l6.9 5.2c1.6-4.7 6.1-8.1 11.3-8.1Z"/></svg>}
function FacebookMark(){return <svg aria-hidden="true" viewBox="0 0 24 24" width="21" height="21"><rect width="24" height="24" rx="5" fill="#0866FF"/><path fill="#fff" d="M13.4 21v-8h2.7l.4-3.1h-3.1v-2c0-.9.3-1.5 1.6-1.5h1.7V3.6c-.3 0-1.3-.1-2.4-.1-2.4 0-4 1.5-4 4.2v2.2H7.6V13h2.7v8h3.1Z"/></svg>}
export default function Welaa(){const path=usePathname()||'/',router=useRouter();const [data,setData]=useState<AppData>(initial),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authOpen,setAuthOpen]=useState(false),[register,setRegister]=useState(false),[authBusy,setAuthBusy]=useState(false);const all=[...spaces,...data.spaces];
const refresh=useCallback(async()=>{try{const [r,{data:{user}}]=await Promise.all([fetch('/api/state',{cache:'no-store'}),supabase.auth.getUser()]),d:any=await r.json();if(!r.ok)throw Error(d.error);setData({...d,user:user?{id:user.id,email:user.email||'',name:user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'สมาชิก WELAA',phone:user.phone||'',bio:''}:null});setError('')}catch(e:any){setError(e.message||'โหลดข้อมูลไม่สำเร็จ')}finally{setReady(true)}},[]);
useEffect(()=>{refresh();const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{const user=session?.user;setData(current=>({...current,user:user?{id:user.id,email:user.email||'',name:user.user_metadata?.full_name||user.user_metadata?.name||user.email?.split('@')[0]||'สมาชิก WELAA',phone:user.phone||'',bio:''}:null}))});const id=setInterval(refresh,60000);return()=>{subscription.unsubscribe();clearInterval(id)}},[refresh]);const auth=(v=false)=>{setRegister(v);setAuthOpen(true)};const go=(p:string)=>router.push(p);
const signInWithProvider=async(provider:'google'|'facebook')=>{setAuthBusy(true);try{const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin+'/'}});if(error)throw error}catch(e:any){toast.error(e.message||'เริ่มเข้าสู่ระบบไม่สำเร็จ');setAuthBusy(false)}};
const act=async(body:any)=>{if(!data.user){auth();return null}setBusy(true);try{const r=await fetch('/api/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result:any=await r.json();if(!r.ok)throw Error(result.error);await refresh();return result}catch(e:any){toast.error(e.message);return null}finally{setBusy(false)}};
const favorite=async(id:string)=>{if(await act({action:'favorite',spaceId:id,saved:!data.favorites.includes(id)}))toast.success(data.favorites.includes(id)?'นำออกจากรายการที่บันทึกแล้ว':'บันทึกพื้นที่แล้ว')};
useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const ac=new AbortController();const defs=[{name:'search_spaces',title:'ค้นหาพื้นที่',description:'Read WELAA spaces matching city and maximum hourly price. Does not book.',inputSchema:{type:'object',properties:{city:{type:'string'},maxPrice:{type:'number',minimum:0}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(x:any)=>{if(!x||typeof x!=='object'||x.maxPrice!==undefined&&(typeof x.maxPrice!=='number'||x.maxPrice<0))throw Error('Invalid input');return all.filter(s=>(!x.city||s.city===x.city)&&(!x.maxPrice||s.price<=x.maxPrice)).map(s=>({id:s.id,name:s.name,price:s.price,city:s.city}))}},{name:'inspect_availability',title:'ดูเวลาว่าง',description:'Read hourly availability and price. Does not reserve.',inputSchema:{type:'object',properties:{spaceId:{type:'string'},date:{type:'string'}},required:['spaceId','date'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(x:any)=>{if(!x||!/^\d{4}-\d{2}-\d{2}$/.test(x.date))throw Error('Invalid date');const s=all.find(s=>s.id===x.spaceId);if(!s)throw Error('Space not found');return Array.from({length:s.close-s.open},(_,i)=>({hour:s.open+i,status:slotStatus(s,x.date,s.open+i,data),price:slotPrice(s,x.date,s.open+i,data)}))}}];for(const t of defs){try{Promise.resolve(mc.registerTool(t,{signal:ac.signal})).catch(()=>{})}catch{}}return()=>ac.abort()},[data]);
let view;if(path==='/')view=<Home/>;else if(path==='/search')view=<SearchPage/>;else if(path.startsWith('/spaces/'))view=<Detail id={path.split('/')[2]}/>;else if(path==='/host/new')view=<Wizard/>;else if(path==='/host/calendar')view=<HostCalendar/>;else if(path==='/account'||path==='/host')view=<Account host={path==='/host'}/>;else if(path==='/how-it-works')view=<HowItWorks/>;else view=<div className="page empty"><h1>ไม่พบหน้านี้</h1><Link className="button" href="/">กลับหน้าหลัก</Link></div>;
return <AppContext.Provider value={{data,all,ready,busy,act,refresh,auth,go,favorite}}><header className="navbar"><Logo/><nav><Link href="/search">ค้นหาพื้นที่</Link><Link href="/#categories">หมวดหมู่</Link><Link href="/how-it-works">วิธีใช้งาน</Link></nav>{data.user?<Link className="account-link" href="/account"><UserRound size={17}/>บัญชีของฉัน</Link>:<button className="login-link" onClick={()=>auth()}>เข้าสู่ระบบ / สมัครสมาชิก</button>}<Link className="button" href="/host/new"><Plus size={17}/>ปล่อยพื้นที่</Link></header>{error&&<div className="data-error">{error} <button className="text-link" onClick={refresh}>ลองใหม่</button></div>}<main>{view}</main><footer className="footer"><div><Logo/><p>พื้นที่มีค่า ทุกเวลา</p></div><div className="footer-links"><Link href="/how-it-works">รู้จัก WELAA</Link><Link href="/host/new">เป็นเจ้าของพื้นที่</Link><Link href="/account?tab=messages">ข้อความ</Link><span>© {new Date().getFullYear()} WELAA</span></div><small className="prototype-note">พื้นที่ตัวอย่าง · การชำระเงินจำลอง</small></footer><nav className="bottom-nav"><Link className={path==='/'?'active':''} href="/"><Compass/>สำรวจ</Link><Link className={path==='/search'?'active':''} href="/search"><Search/>ค้นหา</Link><Link className="add-nav" href="/host/new"><Plus/>ปล่อยพื้นที่</Link><Link href="/account?tab=bookings"><CalendarDays/>การจอง</Link><Link href="/account"><UserRound/>โปรไฟล์</Link></nav><Dialog open={authOpen} onOpenChange={setAuthOpen}><DialogContent><Logo/><DialogTitle className="auth-title">{register?'เริ่มต้นเวลาดี ๆ กับ WELAA':'ยินดีต้อนรับกลับ'}</DialogTitle><DialogDescription>เข้าสู่ระบบหรือสมัครสมาชิกด้วยบัญชี Google หรือ Facebook</DialogDescription><div className="auth-providers"><button type="button" className="button full provider-google" disabled={authBusy} onClick={()=>signInWithProvider('google')}>{authBusy?<span className="provider-loading">กำลังเชื่อมต่อ…</span>:<><GoogleMark/>{register?'สมัครสมาชิกด้วย Google':'เข้าสู่ระบบด้วย Google'}</>}</button><button type="button" className="button full provider-facebook" disabled={authBusy} onClick={()=>signInWithProvider('facebook')}>{authBusy?<span className="provider-loading">กำลังเชื่อมต่อ…</span>:<><FacebookMark/>{register?'สมัครสมาชิกด้วย Facebook':'เข้าสู่ระบบด้วย Facebook'}</>}</button></div><p className="small muted">สมัครสมาชิกหรือเข้าสู่ระบบด้วยบัญชีเดียวกันได้อย่างปลอดภัย</p><button className="text-link" onClick={()=>setRegister(!register)}>{register?'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ':'ยังไม่มีบัญชี? สมัครสมาชิก'}</button></DialogContent></Dialog><Toaster position="top-center" richColors/></AppContext.Provider>}
