'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowLeft,ArrowRight,Check,UploadCloud,X,ShieldCheck,Loader2,Users,CalendarDays} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {toast} from 'sonner';
import {useApp} from './context';
import {Choice,Check as CheckField} from './ui';
import {categories,types,cities,facilities,datePlus,today,hour,money,thaiDate} from './data';
import {supabase} from '@/lib/supabase/client';
const blank=()=>({step:0,name:'',type:'สตูดิโอ',images:[] as string[],activities:[] as string[],city:'หาดใหญ่',area:'',guests:6,date:datePlus(1),open:9,close:18,price:180,rules:'ไม่สูบบุหรี่ภายในพื้นที่ • รักษาความสะอาด • งดเสียงดังหลัง 21:00',description:'',amenities:['Wi-Fi'],rights:false,host:''});
const headings=['พื้นที่ของคุณคืออะไร?','ให้ภาพเล่าเรื่องพื้นที่','ที่นี่ใช้ทำอะไรได้บ้าง?','พื้นที่ของคุณอยู่ที่ไหน?','ชวนมาได้กี่คน?','เมื่อไหร่ที่พื้นที่ของคุณว่าง?','ตั้งราคาที่สบายใจ','กติกาชัดเจน สบายใจทั้งสองฝ่าย','ดูพื้นที่ของคุณก่อนเผยแพร่','พร้อมเปิดพื้นที่ของคุณแล้ว'];
const hints=['ไม่ต้องเป็นสถานที่ใหญ่ แค่มุมที่พร้อมสำหรับใครสักคน','ภาพสว่างที่เห็นพื้นที่จริง ช่วยให้ตัดสินใจได้ง่ายขึ้น','เลือกกิจกรรมที่เหมาะกับพื้นที่และไม่รบกวนเพื่อนบ้าน','ระบุย่านให้ผู้เช่าเห็นภาพว่าเดินทางอย่างไร','จำนวนสูงสุดที่ใช้งานได้อย่างสบายและปลอดภัย','เริ่มจากวันแรกก่อน แล้วเพิ่มวันอื่นในปฏิทินภายหลัง','ราคาต่อชั่วโมงที่ตั้งเอง และปรับตามช่วงเวลาได้','บอกสิ่งที่ทำได้และสิ่งที่ควรหลีกเลี่ยงก่อนจอง','ตรวจรูป รายละเอียด และเวลาว่างให้ครบ','ยืนยันว่าคุณมีสิทธิ์นำพื้นที่นี้มาให้ผู้อื่นใช้งาน'];
export function Wizard(){const {data,ready,auth,act,busy,go,authReady}=useApp();const [draft,setDraft]=useState(blank),[loaded,setLoaded]=useState(false),[save,setSave]=useState(''),[uploading,setUploading]=useState(false),[published,setPublished]=useState('');const init=useRef(false),saving=useRef<Promise<any>|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null);useEffect(()=>{if(ready&&data.user&&!init.current){setDraft({...blank(),...(data.draft||{})});init.current=true;setLoaded(true)}},[ready,data.draft,data.user?.id]);useEffect(()=>{if(!loaded||!data.user||published)return;setSave('กำลังบันทึก…');timer.current=setTimeout(()=>{try{window.localStorage.setItem('welaa-draft',JSON.stringify(draft));setSave('บันทึกฉบับร่างแล้ว')}catch{setSave('บันทึกไม่สำเร็จ · พื้นที่จัดเก็บอุปกรณ์เต็ม')}},650);return()=>{if(timer.current)clearTimeout(timer.current)}},[draft,loaded,data.user?.id,published]);const set=(k:string,v:any)=>setDraft(d=>({...d,[k]:v})),step=draft.step;const valid=[!!draft.name.trim(),draft.images.length>0,draft.activities.length>0,!!draft.area.trim(),Number.isInteger(draft.guests)&&draft.guests>0&&draft.guests<=500,draft.date>=today()&&draft.open<draft.close,draft.price>=1&&draft.price<=100000,!!draft.rules.trim(),true,draft.rights][step];async function upload(files:FileList|null){if(!files)return;if(draft.images.length+files.length>8){toast.error('อัปโหลดได้สูงสุด 8 รูป');return}setUploading(true);const urls:string[]=[];try{for(const f of Array.from(files)){if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>5*1024*1024)throw Error('เลือกรูป JPG, PNG หรือ WebP ขนาดไม่เกิน 5 MB');const ext=f.type==='image/jpeg'?'jpg':f.type==='image/png'?'png':'webp',path=`${data.user!.id}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('listing-images').upload(path,f,{cacheControl:'3600',contentType:f.type,upsert:false});if(error)throw error;urls.push(path)}toast.success('อัปโหลดภาพแล้ว')}catch(e:any){toast.error(e.message||'อัปโหลดภาพไม่สำเร็จ')}finally{setDraft(d=>({...d,images:[...d.images,...urls]}));setUploading(false)}}
if(!authReady)return <div className="page auth-gate" aria-busy="true"><p className="muted">กำลังตรวจสอบบัญชี…</p></div>;if(!data.user)return <div className="page auth-gate"><div className="eyebrow">LET YOUR SPACE DO MORE</div><h1>เริ่มต้นจากพื้นที่ที่คุณมี</h1><p>เข้าสู่ระบบเพื่อบันทึกฉบับร่าง อัปโหลดภาพ และเริ่มปล่อยพื้นที่</p><button className="button" onClick={()=>auth(true)}>สมัครสมาชิก / เข้าสู่ระบบ <ArrowRight size={17}/></button><img src="/photos/cafe.jpg" alt="พื้นที่คาเฟ่"/></div>;
if(published)return <div className="page publish-success"><div className="success-icon"><Check size={28}/></div><h1>พื้นที่ของคุณพร้อมแล้ว</h1><p className="muted">{draft.name} เปิดให้ค้นหาและทดลองจองได้แล้ว</p><img src={supabase.storage.from('listing-images').getPublicUrl(draft.images[0]).data.publicUrl} alt={draft.name}/><div className="row"><button className="button" onClick={()=>go('/spaces/'+published)}>ดูพื้นที่ของฉัน</button><button className="button secondary" onClick={()=>go('/host/calendar?space='+published)}>จัดการเวลาว่าง</button></div></div>;
return <div className="page wizard-page"><aside className="wizard-sidebar"><div className="eyebrow">A NEW POSSIBILITY</div><h2>พื้นที่ของคุณ<br/>เวลาของคุณ</h2><p>เปลี่ยนช่วงที่ว่าง<br/>ให้เป็นโอกาสดี ๆ</p><ol>{['รายละเอียดพื้นที่','รูปภาพ','กิจกรรม','สถานที่','จำนวนคน','เวลาว่าง','ราคา','กฎการใช้พื้นที่','ดูตัวอย่าง','เผยแพร่'].map((s,i)=><li key={s} className={i===step?'active':i<step?'done':''}><span>{i<step?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{s}</li>)}</ol><p className="small muted">กำหนดทุกอย่างได้ด้วยตัวคุณเอง</p></aside><div className="wizard-main"><div className="row between small"><span>ขั้นตอน {step+1} จาก 10</span><span className="muted">{save}</span></div><Progress value={(step+1)*10}/><h1>{headings[step]}</h1><p className="muted wizard-hint">{hints[step]}</p><div className="wizard-body">
{step===0&&<div className="stack"><label className="field">ชื่อพื้นที่<input value={draft.name} onChange={e=>set('name',e.target.value)} maxLength={100} placeholder="เช่น มุมแสงเช้า สตูดิโอ"/></label><label className="field">ประเภทพื้นที่<Choice value={draft.type} onChange={v=>set('type',v)} label="ประเภทพื้นที่" options={types}/></label><label className="field">แนะนำพื้นที่<textarea value={draft.description} onChange={e=>set('description',e.target.value)} maxLength={2000} placeholder="อะไรทำให้พื้นที่นี้พิเศษ? แสง บรรยากาศ หรือทำเล…"/></label></div>}
{step===1&&<><label className="upload-zone"><UploadCloud size={36}/><b>{uploading?'กำลังอัปโหลด…':'เลือกรูปพื้นที่ของคุณ'}</b><span>JPG, PNG, WebP · ไม่เกิน 5 MB / รูป · สูงสุด 8 รูป</span><input aria-label="อัปโหลดรูปพื้นที่" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={uploading} onChange={e=>upload(e.target.files)}/></label><div className="upload-grid">{draft.images.map((url,i)=><div key={url}><img src={supabase.storage.from('listing-images').getPublicUrl(url).data.publicUrl} alt={`ภาพพื้นที่ ${i+1}`}/><span>{i===0?'ภาพหน้าปก':i+1}</span><button aria-label={'ลบภาพ '+(i+1)} onClick={()=>set('images',draft.images.filter(x=>x!==url))}><X size={16}/></button></div>)}</div></>}
{step===2&&<><div className="selection-grid">{categories.slice(1).map(c=><CheckField key={c} checked={draft.activities.includes(c)} onChange={v=>set('activities',v?[...draft.activities,c]:draft.activities.filter(x=>x!==c))}>{c}</CheckField>)}</div><h3 className="mt">สิ่งอำนวยความสะดวก</h3><div className="selection-grid mt">{facilities.map(c=><CheckField key={c} checked={draft.amenities.includes(c)} onChange={v=>set('amenities',v?[...draft.amenities,c]:draft.amenities.filter(x=>x!==c))}>{c}</CheckField>)}</div></>}
{step===3&&<div className="stack"><label className="field">เมือง<Choice value={draft.city} onChange={v=>set('city',v)} label="เมือง" options={cities}/></label><label className="field">ย่าน / ที่อยู่<input value={draft.area} onChange={e=>set('area',e.target.value)} maxLength={100} placeholder="เช่น คอหงส์ ใกล้ ม.อ."/></label><p className="notice">ระบุการเดินทางในคำอธิบาย และตกลงจุดนัดพบกับผู้เช่าผ่านข้อความ</p></div>}
{step===4&&<div className="guest-picker"><Users size={38}/><h3>จำนวนคนสูงสุด</h3><div className="counter"><button aria-label="ลดจำนวนคน" disabled={draft.guests<=1} onClick={()=>set('guests',draft.guests-1)}>−</button><input aria-label="จำนวนคนสูงสุด" type="number" min="1" max="500" value={draft.guests} onChange={e=>set('guests',Number(e.target.value))}/><button aria-label="เพิ่มจำนวนคน" disabled={draft.guests>=500} onClick={()=>set('guests',draft.guests+1)}>+</button></div><p className="small muted">รวมผู้ใช้งานทุกคนในพื้นที่</p></div>}
{step===5&&<div className="stack"><label className="field">วันแรกที่เปิดให้ใช้งาน<input type="date" min={today()} value={draft.date} onChange={e=>set('date',e.target.value)}/></label><div className="two-col"><label className="field">เริ่ม<Choice value={String(draft.open)} onChange={v=>set('open',Number(v))} label="เวลาเปิด" options={Array.from({length:24},(_,h)=>({value:String(h),label:hour(h)}))}/></label><label className="field">สิ้นสุด<Choice value={String(draft.close)} onChange={v=>set('close',Number(v))} label="เวลาปิด" options={Array.from({length:24},(_,i)=>({value:String(i+1),label:hour(i+1)}))}/></label></div><p className="notice">เปิดเฉพาะวันที่เลือก คุณเพิ่มวัน เปิด–ปิดชั่วโมง และตั้งราคาพิเศษได้หลังเผยแพร่</p></div>}
{step===6&&<div className="stack"><label className="field">ราคาต่อชั่วโมง (บาท)<div className="price-input"><span>฿</span><input type="number" min="1" max="100000" value={draft.price} onChange={e=>set('price',Number(e.target.value))}/><span>/ ชั่วโมง</span></div></label><div className="outline-panel price-breakdown"><div><span>ผู้เช่าจอง 2 ชั่วโมง</span><b>฿{money(draft.price*2)}</b></div><div><span>ค่าบริการผู้เช่า 8%</span><b>฿{money(Math.round(draft.price*2*.08))}</b></div><p className="small muted">รุ่นทดลองยังไม่มีการรับหรือโอนเงินจริง</p></div></div>}
{step===7&&<div className="stack"><label className="field">กฎการใช้พื้นที่<textarea rows={6} maxLength={2000} value={draft.rules} onChange={e=>set('rules',e.target.value)}/></label><p className="small muted">ระบุสูบบุหรี่ อาหาร สัตว์เลี้ยง เสียงดัง และกิจกรรมที่ห้าม ใช้ • แยกแต่ละข้อ</p><label className="field">ชื่อเจ้าของที่แสดง<input value={draft.host} maxLength={80} onChange={e=>set('host',e.target.value)} placeholder={data.user.name}/></label></div>}
{step===8&&<div className="listing-preview"><img src={draft.images[0]} alt={draft.name}/><div className="row between wrap"><h2>{draft.name}</h2><b>฿{money(draft.price)} / ชม.</b></div><p className="muted">{draft.area} · {draft.city} · สูงสุด {draft.guests} คน</p><p>{draft.description}</p><div className="row wrap">{draft.activities.map(a=><span className="pill" key={a}>{a}</span>)}</div><p><CalendarDays size={17}/>{thaiDate(draft.date)} · {hour(draft.open)}–{hour(draft.close)}</p><p className="small muted">{draft.rules}</p></div>}
{step===9&&<div className="stack"><div className="publish-summary"><ShieldCheck size={40}/><h2>พื้นที่เล็ก ๆ ของคุณ<br/>อาจเป็นโอกาสใหญ่ของใครสักคน</h2><p className="muted">{draft.name} · {draft.city}</p></div><CheckField checked={draft.rights} onChange={v=>set('rights',v)}>ฉันเป็นเจ้าของหรือได้รับอนุญาตให้ปล่อยพื้นที่นี้ และตรวจสอบข้อกำหนดอาคาร คอนโด หรือสัญญาเช่าแล้ว</CheckField><p className="notice">ประกาศจะแสดงในหน้าค้นหา รุ่นทดลองรองรับการจองและชำระเงินจำลองเท่านั้น</p></div>}
</div><div className="wizard-actions"><button className="button secondary" disabled={step===0||busy} onClick={()=>set('step',step-1)}><ArrowLeft size={16}/>ย้อนกลับ</button>{step<9?<button className="button" disabled={!valid||uploading} onClick={()=>set('step',step+1)}>ถัดไป<ArrowRight size={16}/></button>:<button className="button" disabled={!valid||busy} onClick={async()=>{if(timer.current)clearTimeout(timer.current);await saving.current;const r=await act({action:'publish',data:draft});if(r)setPublished(r.id)}}>{busy?<Loader2 className="spin" size={17}/>:<Check size={17}/>}เผยแพร่พื้นที่</button>}</div></div></div>}
